version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      #- run:
          #name: Pulling the Docker Image
          #command: docker pull jeremysouche/node-js-sample:latest
      - run:
          name: Building Image
          command: docker build -t node-js-sample .
      - run: 
          name: Creating the container
          command: docker run -p 8080:8080 -d --name node-js-app jeremysouche/node-js-sample:latest
      - run: 
          name: Validate that service is working
          command: |
            docker container run --network container:node-js-app \
            docker.io/jwilder/dockerize \
            -wait http://localhost:8080 \
            -wait-retry-interval 2s \
            -timeout 20s
      - run:
          name: Publish Docker image
          command: |
            echo "u@i4BK%smW93Xa6p" | docker login --username "jeremysouche" --password-stdin
            docker push "jeremysouche/node-js-sample" 

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
