version: 2.1

jobs:
  build:
    docker:
      - image: jeremysouche/node-js-sample:latest
    steps:
      - checkout

      - run:
          name: Waiting for the web server to be ready
          command: dockerize -wait http://localhost:8080 -timeout 1m 

      - run:
          name: Validate service is working
          command: |
            if [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)" != "200" ]; then
              echo "Application did not return HTTP 200 OK."
              exit 1
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
