version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    resource_class: large
    steps:
      - run: 
          name: Pulling the Docker Image
          command: docker pull jeremysouche/node-js-sample:latest
      - run: 
          name: Creating the container
          command: docker run -p 8080:8080 -d --name node-js-app jeremysouche/node-js-sample:latest
      #- run:
          #name: Validate that service is working
          #command: docker exec -it node-js-app curl http://localhost:8080
      - run: 
          name: Validate that service is working
          command: |
            docker container run --network container:node-js-app \
            docker.io/jwilder/dockerize \
            -wait http://localhost:8080 \
            -wait-retry-interval 5s \
            -timeout 30s

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
